services:
  app:
    container_name: app
    image: ghcr.io/jankku/eino-backend:master
    ports:
      - '127.0.0.1:5000:5000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file: .env
    entrypoint: '/bin/ash docker-entrypoint.sh'
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
