services:
  app:
    container_name: app
    image: ghcr.io/jankku/eino-backend:master
    ports:
      - '127.0.0.1:5000:5000'
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file: .env
    entrypoint: '/bin/ash docker-entrypoint.sh'
    depends_on:
      - database
    volumes:
      - profilepicture:/home/node/eino/profilepicture/

  database:
    container_name: database
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    volumes:
      - database-data:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    image: fholzer/nginx-brotli:v1.26.2
    ports:
      - '127.0.0.1:8443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/jankku.fi:/etc/letsencrypt/live/jankku.fi:ro
      - /etc/letsencrypt/archive/jankku.fi:/etc/letsencrypt/archive/jankku.fi:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
volumes:
  database-data:
  profilepicture:
