version: "3.9"

services:
    app:
        container_name: app
        build: .
        ports:
            - "3000:3000"
        working_dir: /usr/src/eino
        environment:
            NODE_ENV: production
        env_file: .env
        depends_on:
            - database
        volumes:
            - ./logs:/usr/src/eino/logs/
    database:
        container_name: database
        image: postgres:latest
        restart: always
        env_file: .env
        volumes:
            - ./database-data:/var/lib/postgresql/data/
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql