version: "3.9"

services:
    app:
        container_name: app
        build: .
        ports:
            - "3000:3000"
        working_dir: /usr/src/entertainmentlist
        environment:
            NODE_ENV: production
            DATABASE_URL: "postgres://database:3001/entertainmentlist"
        env_file: .env
        depends_on:
            - database
    database:
        container_name: database
        image: postgres:latest
        restart: always
        ports:
            - "3001:5432"
        env_file: .env
        volumes:
            - ./database-data:/var/lib/postgresql/data/